"""Phase 5: TTM-inspired memory-proxy self-test."""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

from qsot2.core.checks import PHASE_CHECKS
from qsot2.model import (
    BACKGROUND_BUILDERS,
    MetricToChannelMap,
    QuantumState,
    compute_memory_kernel,
)

if TYPE_CHECKING:
    from qsot2.core.phase_context import PhaseContext


def run_phase5(ctx: PhaseContext) -> None:
    """Execute Phase 5 checks."""
    state0 = QuantumState.from_bloch(np.pi / 2, 0.0).rho  # |+>
    bg_flat = BACKGROUND_BUILDERS["flat"](10)
    bg_schwarz = BACKGROUND_BUILDERS["schwarzschild"](10)
    mapper = MetricToChannelMap(sensitivity=ctx.config.sensitivity)
    ch_identity = mapper.to_channel(bg_flat)
    ch_dephasing = mapper.to_channel(bg_schwarz, channel_type="dephasing")

    # --- TTM category 1: detector self-test on a SYNTHETIC injected backflow ---
    # The third state is state0 reappearing -- an artificial coherence revival the
    # configured channels do not produce. A PASS validates that the TTM detector
    # registers non-Markovian backflow; it is NOT evidence that the model exhibits
    # non-Markovian physics.
    synthetic_traj = [
        state0,
        ch_dephasing.apply(state0),
        state0,  # artificial coherence backflow (injected, not model-produced)
    ]
    synthetic_channels = [ch_dephasing, ch_identity]
    # Detector self-test threshold is curvature-agnostic by design: the injected
    # backflow validates the detector, not any curved background, so the flat
    # reference (ricci_norm=0.0 -> threshold_curvature_engaged=False) is used.
    selftest = compute_memory_kernel(synthetic_traj, synthetic_channels, ricci_norm=0.0)
    selftest["source"] = "synthetic_injected_backflow"
    selftest["channel_sensitivity"] = ctx.config.sensitivity
    selftest["interpretation"] = (
        "Detector self-test: an artificial coherence backflow is injected to confirm "
        "the TTM registers nm > 0. Validates the detector only; not evidence that the "
        "model exhibits non-Markovian physics."
    )
    ctx.result.checks["memory_kernel_selftest_detects_injected_backflow"] = (
        "PASS" if selftest["nm_measure"] > 0.0 else "FAIL"
    )
    ctx.result.observations["memory_kernel"] = selftest

    # --- TTM category 2: the model's OWN trajectory (phenomenological output) ---
    # Generated by applying the configured channel consistently, with no injected
    # revival. The phenomenological map is Markovian by construction, so the model
    # trajectory exhibits no non-Markovian backflow (nm ~ 0).
    model_traj = [
        state0,
        ch_dephasing.apply(state0),
        ch_dephasing.apply(ch_dephasing.apply(state0)),
    ]
    model_channels = [ch_dephasing, ch_dephasing]
    # Threshold provenance: feed the Schwarzschild channel's own Ricci norm rather
    # than a hardcoded 0.0 (DI-004). Schwarzschild is Ricci-flat, so this is 0.0 and
    # the threshold reduces to the flat reference -- now surfaced, not hidden.
    model_mem = compute_memory_kernel(model_traj, model_channels, ricci_norm=bg_schwarz.ricci_norm)
    model_mem["source"] = "model_generated_trajectory"
    model_mem["channel_sensitivity"] = ctx.config.sensitivity
    model_mem["interpretation"] = (
        "The phenomenological channel map is Markovian by construction; the model's "
        "own trajectory exhibits no non-Markovian backflow (nm ~ 0)."
    )
    ctx.result.observations["memory_kernel_model_trajectory"] = model_mem


def skip_phase5(ctx: PhaseContext) -> None:
    """Skip Phase 5 checks."""
    for c in PHASE_CHECKS["phase5_ttm_accessibility"]:
        ctx.result.checks[c] = "SKIPPED"
